[build]
  publish = "out"
  command = "npm run build"

# Handle static assets first
[[redirects]]
  from = "/favicon.svg"
  to = "/favicon.svg"
  status = 200

# Handle other static assets
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Handle admin login route specifically
[[redirects]]
  from = "/admin/login"
  to = "/admin/login.html"
  status = 200
  force = true

# Handle admin dashboard route specifically
[[redirects]]
  from = "/admin/dashboard"
  to = "/admin/dashboard.html"
  status = 200
  force = true

# Handle admin dashboard subroutes
[[redirects]]
  from = "/admin/dashboard/*"
  to = "/admin/dashboard/:splat.html"
  status = 200
  force = true

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyBq35ZerGqkdJqK-rHoK7cCb1lzjZFMAxk"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "prarambh-bca.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "prarambh-bca"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "prarambh-bca.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "872449639174"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:872449639174:web:e84997ef5ad97121239487"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-2JFD7NT2P0"
